curl https://fonts.gstatic.com/s/saira/v3/mem-Ya2wxmKQyNFEfZ41V4Uf.woff2 > saira-thin-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem-Ya2wxmKQyNFEfZ81V4Uf.woff2 > saira-thin-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem-Ya2wxmKQyNFEfZE1Vw.woff2 > saira-thin-latin-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem9Ya2wxmKQyNHobIYdcrgmVA.woff2 > saira-extralight-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem9Ya2wxmKQyNHobIYccrgmVA.woff2 > saira-extralight-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem9Ya2wxmKQyNHobIYScrg.woff2 > saira-extralight-latin-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem9Ya2wxmKQyNGMb4YdcrgmVA.woff2 > saira-light-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem9Ya2wxmKQyNGMb4YccrgmVA.woff2 > saira-light-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem9Ya2wxmKQyNGMb4YScrg.woff2 > saira-light-latin-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/memwYa2wxmKQyNkoTZMtUw.woff2 > saira-regular-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/memwYa2wxmKQyNkpTZMtUw.woff2 > saira-regular-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/memwYa2wxmKQyNknTZM.woff2 > saira-regular-latin-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem9Ya2wxmKQyNHUboYdcrgmVA.woff2 > saira-medium-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem9Ya2wxmKQyNHUboYccrgmVA.woff2 > saira-medium-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem9Ya2wxmKQyNHUboYScrg.woff2 > saira-medium-latin-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem9Ya2wxmKQyNH4aYYdcrgmVA.woff2 > saira-semibold-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem9Ya2wxmKQyNH4aYYccrgmVA.woff2 > saira-semibold-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem9Ya2wxmKQyNH4aYYScrg.woff2 > saira-semibold-latin-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem9Ya2wxmKQyNGcaIYdcrgmVA.woff2 > saira-bold-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem9Ya2wxmKQyNGcaIYccrgmVA.woff2 > saira-bold-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem9Ya2wxmKQyNGcaIYScrg.woff2 > saira-bold-latin-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem9Ya2wxmKQyNGAa4YdcrgmVA.woff2 > saira-extrabold-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem9Ya2wxmKQyNGAa4YccrgmVA.woff2 > saira-extrabold-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem9Ya2wxmKQyNGAa4YScrg.woff2 > saira-extrabold-latin-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem9Ya2wxmKQyNGkaoYdcrgmVA.woff2 > saira-black-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem9Ya2wxmKQyNGkaoYccrgmVA.woff2 > saira-black-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/saira/v3/mem9Ya2wxmKQyNGkaoYScrg.woff2 > saira-black-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRMQgErUN8XuHNEtX81i9TmEkrnwdtI0Iiirw.woff2 > saira-condensed-thin-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRMQgErUN8XuHNEtX81i9TmEkrnwdtJ0Iiirw.woff2 > saira-condensed-thin-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRMQgErUN8XuHNEtX81i9TmEkrnwdtH0Ig.woff2 > saira-condensed-thin-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRLQgErUN8XuHNEtX81i9TmEkrnbcpQ-K2fli0.woff2 > saira-condensed-extralight-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRLQgErUN8XuHNEtX81i9TmEkrnbcpQ-a2fli0.woff2 > saira-condensed-extralight-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRLQgErUN8XuHNEtX81i9TmEkrnbcpQ962f.woff2 > saira-condensed-extralight-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRLQgErUN8XuHNEtX81i9TmEkrnCclQ-K2fli0.woff2 > saira-condensed-light-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRLQgErUN8XuHNEtX81i9TmEkrnCclQ-a2fli0.woff2 > saira-condensed-light-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRLQgErUN8XuHNEtX81i9TmEkrnCclQ962f.woff2 > saira-condensed-light-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJROQgErUN8XuHNEtX81i9TmEkrvretFyIw.woff2 > saira-condensed-regular-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJROQgErUN8XuHNEtX81i9TmEkrvrOtFyIw.woff2 > saira-condensed-regular-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJROQgErUN8XuHNEtX81i9TmEkrvoutF.woff2 > saira-condensed-regular-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRLQgErUN8XuHNEtX81i9TmEkrnUchQ-K2fli0.woff2 > saira-condensed-medium-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRLQgErUN8XuHNEtX81i9TmEkrnUchQ-a2fli0.woff2 > saira-condensed-medium-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRLQgErUN8XuHNEtX81i9TmEkrnUchQ962f.woff2 > saira-condensed-medium-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRLQgErUN8XuHNEtX81i9TmEkrnfc9Q-K2fli0.woff2 > saira-condensed-semibold-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRLQgErUN8XuHNEtX81i9TmEkrnfc9Q-a2fli0.woff2 > saira-condensed-semibold-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRLQgErUN8XuHNEtX81i9TmEkrnfc9Q962f.woff2 > saira-condensed-semibold-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRLQgErUN8XuHNEtX81i9TmEkrnGc5Q-K2fli0.woff2 > saira-condensed-bold-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRLQgErUN8XuHNEtX81i9TmEkrnGc5Q-a2fli0.woff2 > saira-condensed-bold-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRLQgErUN8XuHNEtX81i9TmEkrnGc5Q962f.woff2 > saira-condensed-bold-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRLQgErUN8XuHNEtX81i9TmEkrnBc1Q-K2fli0.woff2 > saira-condensed-extrabold-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRLQgErUN8XuHNEtX81i9TmEkrnBc1Q-a2fli0.woff2 > saira-condensed-extrabold-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRLQgErUN8XuHNEtX81i9TmEkrnBc1Q962f.woff2 > saira-condensed-extrabold-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRLQgErUN8XuHNEtX81i9TmEkrnIcxQ-K2fli0.woff2 > saira-condensed-black-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRLQgErUN8XuHNEtX81i9TmEkrnIcxQ-a2fli0.woff2 > saira-condensed-black-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairacondensed/v4/EJRLQgErUN8XuHNEtX81i9TmEkrnIcxQ962f.woff2 > saira-condensed-black-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFsOHYr-vcC7h8MklGBkrvmUG9rbpkisrTri3j5_C9csw.woff2 > saira-extracondensed-thin-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFsOHYr-vcC7h8MklGBkrvmUG9rbpkisrTri3j4_C9csw.woff2 > saira-extracondensed-thin-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFsOHYr-vcC7h8MklGBkrvmUG9rbpkisrTri3j2_C8.woff2 > saira-extracondensed-thin-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFvOHYr-vcC7h8MklGBkrvmUG9rbpkisrTrJ2nh1Aphim8.woff2 > saira-extracondensed-extralight-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFvOHYr-vcC7h8MklGBkrvmUG9rbpkisrTrJ2nh1Qphim8.woff2 > saira-extracondensed-extralight-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFvOHYr-vcC7h8MklGBkrvmUG9rbpkisrTrJ2nh2wph.woff2 > saira-extracondensed-extralight-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFvOHYr-vcC7h8MklGBkrvmUG9rbpkisrTrQ2rh1Aphim8.woff2 > saira-extracondensed-light-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFvOHYr-vcC7h8MklGBkrvmUG9rbpkisrTrQ2rh1Qphim8.woff2 > saira-extracondensed-light-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFvOHYr-vcC7h8MklGBkrvmUG9rbpkisrTrQ2rh2wph.woff2 > saira-extracondensed-light-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFiOHYr-vcC7h8MklGBkrvmUG9rbpkisrTj50j05Cs.woff2 > saira-extracondensed-regular-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFiOHYr-vcC7h8MklGBkrvmUG9rbpkisrTj5kj05Cs.woff2 > saira-extracondensed-regular-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFiOHYr-vcC7h8MklGBkrvmUG9rbpkisrTj6Ej0.woff2 > saira-extracondensed-regular-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFvOHYr-vcC7h8MklGBkrvmUG9rbpkisrTrG2vh1Aphim8.woff2 > saira-extracondensed-medium-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFvOHYr-vcC7h8MklGBkrvmUG9rbpkisrTrG2vh1Qphim8.woff2 > saira-extracondensed-medium-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFvOHYr-vcC7h8MklGBkrvmUG9rbpkisrTrG2vh2wph.woff2 > saira-extracondensed-medium-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFvOHYr-vcC7h8MklGBkrvmUG9rbpkisrTrN2zh1Aphim8.woff2 > saira-extracondensed-semibold-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFvOHYr-vcC7h8MklGBkrvmUG9rbpkisrTrN2zh1Qphim8.woff2 > saira-extracondensed-semibold-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFvOHYr-vcC7h8MklGBkrvmUG9rbpkisrTrN2zh2wph.woff2 > saira-extracondensed-semibold-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFvOHYr-vcC7h8MklGBkrvmUG9rbpkisrTrU23h1Aphim8.woff2 > saira-extracondensed-bold-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFvOHYr-vcC7h8MklGBkrvmUG9rbpkisrTrU23h1Qphim8.woff2 > saira-extracondensed-bold-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFvOHYr-vcC7h8MklGBkrvmUG9rbpkisrTrU23h2wph.woff2 > saira-extracondensed-bold-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFvOHYr-vcC7h8MklGBkrvmUG9rbpkisrTrT27h1Aphim8.woff2 > saira-extracondensed-extrabold-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFvOHYr-vcC7h8MklGBkrvmUG9rbpkisrTrT27h1Qphim8.woff2 > saira-extracondensed-extrabold-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFvOHYr-vcC7h8MklGBkrvmUG9rbpkisrTrT27h2wph.woff2 > saira-extracondensed-extrabold-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFvOHYr-vcC7h8MklGBkrvmUG9rbpkisrTra2_h1Aphim8.woff2 > saira-extracondensed-black-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFvOHYr-vcC7h8MklGBkrvmUG9rbpkisrTra2_h1Qphim8.woff2 > saira-extracondensed-black-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairaextracondensed/v4/-nFvOHYr-vcC7h8MklGBkrvmUG9rbpkisrTra2_h2wph.woff2 > saira-extracondensed-black-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MN6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXdvWOs2rET-.woff2 > saira-semicondensed-thin-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MN6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXdvWOo2rET-.woff2 > saira-semicondensed-thin-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MN6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXdvWOQ2rA.woff2 > saira-semicondensed-thin-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MM6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXfDSfMeiXnH6A.woff2 > saira-semicondensed-extralight-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MM6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXfDSfMfiXnH6A.woff2 > saira-semicondensed-extralight-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MM6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXfDSfMRiXk.woff2 > saira-semicondensed-extralight-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MM6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXenSvMeiXnH6A.woff2 > saira-semicondensed-light-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MM6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXenSvMfiXnH6A.woff2 > saira-semicondensed-light-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MM6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXenSvMRiXk.woff2 > saira-semicondensed-light-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MD6c-2-nnJkHxyCjRcnMHcWVWV1cWRRX8DaOYuqA.woff2 > saira-semicondensed-regular-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MD6c-2-nnJkHxyCjRcnMHcWVWV1cWRRX8CaOYuqA.woff2 > saira-semicondensed-regular-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MD6c-2-nnJkHxyCjRcnMHcWVWV1cWRRX8MaOY.woff2 > saira-semicondensed-regular-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MM6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXf_S_MeiXnH6A.woff2 > saira-semicondensed-medium-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MM6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXf_S_MfiXnH6A.woff2 > saira-semicondensed-medium-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MM6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXf_S_MRiXk.woff2 > saira-semicondensed-medium-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MM6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXfTTPMeiXnH6A.woff2 > saira-semicondensed-semibold-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MM6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXfTTPMfiXnH6A.woff2 > saira-semicondensed-semibold-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MM6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXfTTPMRiXk.woff2 > saira-semicondensed-semibold-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MM6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXe3TfMeiXnH6A.woff2 > saira-semicondensed-bold-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MM6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXe3TfMfiXnH6A.woff2 > saira-semicondensed-bold-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MM6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXe3TfMRiXk.woff2 > saira-semicondensed-bold-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MM6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXerTvMeiXnH6A.woff2 > saira-semicondensed-extrabold-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MM6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXerTvMfiXnH6A.woff2 > saira-semicondensed-extrabold-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MM6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXerTvMRiXk.woff2 > saira-semicondensed-extrabold-latin-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MM6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXePT_MeiXnH6A.woff2 > saira-semicondensed-black-vietnamese-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MM6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXePT_MfiXnH6A.woff2 > saira-semicondensed-black-latin-ext-normal.woff2
curl https://fonts.gstatic.com/s/sairasemicondensed/v4/U9MM6c-2-nnJkHxyCjRcnMHcWVWV1cWRRXePT_MRiXk.woff2 > saira-semicondensed-black-latin-normal.woff2
